### PR TITLE
Update dependencies and change README.md mirroring http4s/http4s.g8

### PR DESCRIPTION
**Pull request by froth**

### CODE REVIEW

**Comment by rossabaker** [comment]
I don't know how much this branch diverged from the Scala 3 branch, but it may be easier to make changes on one and merge to the other.

**Comment by froth** [comment]
That makes sense, I will have a look and see if they are still similar enough.

**Review by rossabaker — APPROVED** [review]

**Comment by froth** [comment]
Merging in the direction from `0.23-scala3` to `0.23` is a lot of pain as it basically migrates to scala-3. I will merge this as is and will try to merge from `0.23 to 0.23-scala3` next time.

**Comment by froth** [comment]
I had a look at merging 0.23 to 0.23-scala3 and it was not a pleasant experience. I think for now we are stuck with multiple work. Maybe in the future it makes sense to restart the other branches from 0.23

**Pull request merged**
